# ~/ansible_devops_project/group_vars/secrets.yml
---
gitlab_root_password: "Lab@1234"
gitlab_pat_token: "glpat-LhXKYTWzfQG5WxhwjzhmTW86MQp1OjIH.01.0w1slrpho"
rancher_admin_password: "Lab@12345678"
grafana_admin_password: "Lab@1234"
jenkins_admin_password: "Lab@1234"
sonarqube_admin_password: "Lab@1234"
sonarqube_db_password: "Lab@1234"